"""Plan 402 T4 — the committed OpenAPI contract for the flow map's routes
ONLY, generated by `build_map_openapi()` and consumed both by the command
that writes `docs/spec/api-v1-map.openapi.json` and by the drift test
(`tests/unit/api/test_map_contract.py`). `openapi_url` stays `None` on the
live app (Plan 147 Slice C) — nothing is served; this is a static artefact.

D14: `info.version` is a hand-maintained constant, never the package
version. Bump the MINOR number for an additive change (new field, route,
enum member); bump the MAJOR number for anything else, and announce it to
the map session before deploy (`tools/check_map_contract_version.py`, the
CI gate on this file, enforces "some version increased" mechanically — NOT
which number moved; that's a review judgement).
"""

from __future__ import annotations

from typing import Any

from fastapi.openapi.utils import get_openapi
from fastapi.routing import APIRoute

from sapphire_flow.api import app
from sapphire_flow.api.schemas import ErrorResponse

MAP_CONTRACT_VERSION = "1.0"

# The exact route set the map reads (plan `Endpoint contract` / T4) — no
# other route may appear in the committed file.
_MAP_ROUTES: frozenset[tuple[str, str]] = frozenset(
    {
        ("GET", "/api/v1/stations"),
        ("GET", "/api/v1/stations/{station_id}"),
        ("GET", "/api/v1/stations/{station_id}/observations"),
        ("GET", "/api/v1/stations/{station_id}/forecasts"),
        ("GET", "/api/v1/forecasts/{forecast_id}"),
        ("GET", "/api/v1/qc/rules"),
        ("GET", "/api/v1/stations/{station_id}/skill"),
    }
)

# The two REVIEW-gated routes (Plan 401/402) — reviewer or admin token only.
_REVIEW_PATHS: frozenset[str] = frozenset(
    {"/api/v1/qc/rules", "/api/v1/stations/{station_id}/skill"}
)

# Every route in _MAP_ROUTES except the station LIST parses at least one
# query value (or a station_id) through a helper that raises HTTPException
# 400 on failure (`api/routes/api_stations.py::_parse_datetime/_parse_enum`,
# `api/routes/api_review.py::_parse_station_id`) — `/stations/{id}` and
# `/forecasts/{id}` parse their path id UNGUARDED today (500 on malformed,
# noted on the consumer page, not changed here).
_400_PATHS: frozenset[str] = frozenset(
    {
        "/api/v1/stations",
        "/api/v1/stations/{station_id}/observations",
        "/api/v1/stations/{station_id}/forecasts",
        "/api/v1/qc/rules",
        "/api/v1/stations/{station_id}/skill",
    }
)

# Every route except the station LIST answers 404 for an unknown or
# out-of-scope station/forecast; the list instead silently filters to the
# principal's scope.
_404_PATHS: frozenset[str] = frozenset(
    {
        "/api/v1/stations/{station_id}",
        "/api/v1/stations/{station_id}/observations",
        "/api/v1/stations/{station_id}/forecasts",
        "/api/v1/forecasts/{forecast_id}",
        "/api/v1/qc/rules",
        "/api/v1/stations/{station_id}/skill",
    }
)

_DESCRIPTIONS: dict[tuple[str, str], str] = {
    ("GET", "/api/v1/stations"): (
        "Lists stations. A consumer, reviewer or admin token may call this; "
        "a consumer/reviewer token's result is silently filtered to its "
        "scoped stations rather than 404ing."
    ),
    ("GET", "/api/v1/stations/{station_id}"): (
        "Station detail. Any authenticated token role may call this; an "
        "out-of-scope or unknown station is 404. A malformed station_id is "
        "unguarded today and returns 500, not 400."
    ),
    ("GET", "/api/v1/stations/{station_id}/observations"): (
        "Observations for a station and parameter window, with QC status "
        "and typed qc_flags. Any authenticated token role may call this; "
        "an out-of-scope or unknown station is 404."
    ),
    ("GET", "/api/v1/stations/{station_id}/forecasts"): (
        "Forecast summaries for a station, with QC status and typed "
        "qc_flags. Any authenticated token role may call this; an "
        "out-of-scope or unknown station is 404."
    ),
    ("GET", "/api/v1/forecasts/{forecast_id}"): (
        "Forecast detail, with typed qc_flags. Any authenticated token "
        "role may call this; an out-of-scope or unknown forecast is 404. A "
        "malformed forecast_id is unguarded today and returns 500, not 400."
    ),
    ("GET", "/api/v1/qc/rules"): (
        "Both QC rule sets as the serving process resolves them now. "
        "REVIEW-gated: a reviewer or admin token only (403 for a consumer "
        "token). Without station_id: deployment-wide, no station data. "
        "With station_id: the observation rules for that station, with the "
        "thresholds ingest applies there merged in — an out-of-scope "
        "station is 404 for a reviewer token, an unknown one 404 for a "
        "reviewer or admin token, a malformed one 400."
    ),
    ("GET", "/api/v1/stations/{station_id}/skill"): (
        "The station's current skill rows on the artifact its forecast "
        "uses. REVIEW-gated: a reviewer or admin token only (403 for a "
        "consumer token). An out-of-scope station is 404 for a reviewer "
        "token, an unknown one 404 for a reviewer or admin token, a "
        "malformed one 400."
    ),
}


def _error_response(description: str) -> dict[str, Any]:
    return {
        "description": description,
        "content": {
            "application/json": {
                "schema": {"$ref": "#/components/schemas/ErrorResponse"}
            }
        },
    }


def _select_routes() -> list[APIRoute]:
    api_routes = [route for route in app.routes if isinstance(route, APIRoute)]
    selected = [
        route
        for route in api_routes
        if any((method, route.path) in _MAP_ROUTES for method in route.methods)
    ]
    found = {
        (method, route.path)
        for route in selected
        for method in route.methods
        if (method, route.path) in _MAP_ROUTES
    }
    missing = _MAP_ROUTES - found
    if missing:
        raise RuntimeError(f"map_contract: routes missing from app.routes: {missing}")
    return selected


def build_map_openapi() -> dict[str, Any]:
    doc = get_openapi(
        title="SAPPHIRE Flow — flow map contract",
        version=MAP_CONTRACT_VERSION,
        description=(
            "The subset of /api/v1 the flow map reads (Plan 402). Not "
            "served — openapi_url stays None on the live app; this is a "
            "committed, drift-tested static artefact. Bearer auth is added "
            "explicitly below: the live routes read the Authorization "
            "header from the raw Request, so FastAPI's own generator sees "
            "no security scheme."
        ),
        routes=_select_routes(),
    )

    doc.setdefault("components", {}).setdefault("schemas", {})["ErrorResponse"] = (
        ErrorResponse.model_json_schema()
    )
    doc["components"]["securitySchemes"] = {
        "bearerAuth": {"type": "http", "scheme": "bearer"}
    }

    paths: dict[str, dict[str, dict[str, Any]]] = doc["paths"]
    for path, path_item in paths.items():
        for method, operation in path_item.items():
            operation["security"] = [{"bearerAuth": []}]
            description = _DESCRIPTIONS.get((method.upper(), path))
            if description is not None:
                operation["description"] = description
            responses: dict[str, Any] = operation.setdefault("responses", {})
            if path in _400_PATHS:
                responses["400"] = _error_response(
                    "Malformed query value or station_id "
                    '(error envelope: {"error": <message>, "detail": null}).'
                )
            responses["401"] = _error_response("Missing or invalid access token.")
            if path in _REVIEW_PATHS:
                responses["403"] = _error_response("Reviewer or admin token required.")
            if path in _404_PATHS:
                responses["404"] = _error_response(
                    "Unknown or out-of-scope station/forecast — the same "
                    "body either way (never reveals which)."
                )

    return doc
